networks:
  playground-network:
    external: true

services:
  ethglobal-taipei:
    container_name: bhsl-webapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_CI_TOKEN=
    env_file:
      - ./.env.docker
    ports:
      - 3000:${PORT}
    networks:
      - playground-network
